# fly.toml app configuration file generated for card-bot on 2023-06-09T17:40:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "card-bot"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:full"

[mounts]
  source="card_bot_data"
  destination="/data"
